import type { KnipConfig } from 'knip';

/**
 * Knip configuration for Academic Explorer monorepo
 *
 * Simplified configuration focusing on core unused file/dependency detection
 * without complex plugin configurations that may have path issues.
 */
const config: KnipConfig = {
  workspaces: {
    // Root workspace - scripts and configs
    ".": {
      entry: [
        "tools/scripts/*.{ts,js}",
        "config/shared.ts",
        "config/vite-plugins/static-data-index.ts",
        "vite.config.ts",
        "nx.json",
        ".lintstagedrc.js"
      ],
      project: [
        "tools/scripts/**/*.{ts,js}",
        "config/**/*.ts",
        "*.{ts,js}"
      ]
    },

    // Web application
    "apps/web": {
      entry: [
        "src/main.tsx",
        "src/test/setup.ts",
        "src/test/component-setup.ts",
        "src/test/e2e-setup.ts",
        "src/test/msw/server.ts",
        "src/test/msw/handlers.ts",
        "src/build-plugins/openalex-data-plugin.ts",
        "src/stores/data-fetching-progress-store.ts"
      ],
      project: [
        "src/**/*.{ts,tsx}"
      ],
      ignore: [
        "src/routeTree.gen.ts", // Generated by TanStack Router
        "src/**/*.{test,spec}.{ts,tsx}",
        "e2e/**/*"
      ]
    },

    // CLI application
    "apps/cli": {
      entry: [
        "src/simple-cli.ts"
      ],
      project: [
        "src/**/*.ts"
      ],
      ignore: [
        "src/**/*.{test,spec}.ts"
      ]
    },

    // Graph package
    "packages/graph": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // Simulation package
    "packages/simulation": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // OpenAlex client package
    "packages/client": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // UI components package
    "packages/ui": {
      entry: [
        "src/index.ts",
        "src/test/setup.ts"
      ],
      project: [
        "src/**/*.{ts,tsx}"
      ],
      ignore: [
        "src/**/*.stories.{ts,tsx}", // Storybook stories
        "src/**/*.{test,spec}.{ts,tsx}"
      ]
    },

    // Shared utilities package
    "packages/utils": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    }
  },

  // Global ignore patterns
  ignore: [
    "**/dist/**",
    "**/coverage/**",
    "**/.nx/**",
    "**/node_modules/**",
    "**/.tmp/**",
    "**/.cache/**",
    ".github/**", // GitHub workflows contain complex YAML that can confuse knip
    ".github/workflows/**"
  ],

  // Plugin configurations
  eslint: {
    config: [
      "eslint.config.base.ts",
      "eslint.config.react.ts",
      "apps/*/eslint.config.ts",
      "packages/*/eslint.config.ts"
    ]
  },
  vitest: {
    config: [
      "vitest.config.base.ts",
      "vitest.config.react.ts",
      "apps/*/vitest.config.ts",
      "packages/*/vitest.config.ts"
    ]
  },

  // Still disabled due to path issues
  vite: false,
  playwright: false
};

export default config;