import type { KnipConfig } from 'knip';

/**
 * Knip configuration for Academic Explorer monorepo
 *
 * Simplified configuration focusing on core unused file/dependency detection
 * without complex plugin configurations that may have path issues.
 */
const config: KnipConfig = {
  workspaces: {
    // Root workspace - scripts and configs
    ".": {
      entry: [
        "scripts/*.{ts,js}",
        "config/shared.ts",
        "vite.config.ts",
        "nx.json",
        ".lintstagedrc.js"
      ],
      project: [
        "scripts/**/*.{ts,js}",
        "config/**/*.ts",
        "*.{ts,js}"
      ]
    },

    // Web application
    "apps/web": {
      entry: [
        "src/main.tsx"
      ],
      project: [
        "src/**/*.{ts,tsx}"
      ],
      ignore: [
        "src/routeTree.gen.ts", // Generated by TanStack Router
        "src/**/*.{test,spec}.{ts,tsx}",
        "e2e/**/*"
      ]
    },

    // CLI application
    "apps/cli": {
      entry: [
        "src/simple-cli.ts"
      ],
      project: [
        "src/**/*.ts"
      ],
      ignore: [
        "src/**/*.{test,spec}.ts"
      ]
    },

    // Graph package
    "packages/graph": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // Simulation package
    "packages/simulation": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // OpenAlex client package
    "packages/openalex-client": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    },

    // UI components package
    "packages/ui-components": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.{ts,tsx}"
      ],
      ignore: [
        "src/**/*.stories.{ts,tsx}", // Storybook stories
        "src/**/*.{test,spec}.{ts,tsx}"
      ]
    },

    // Shared utilities package
    "packages/shared-utils": {
      entry: [
        "src/index.ts"
      ],
      project: [
        "src/**/*.ts"
      ]
    }
  },

  // Global ignore patterns
  ignore: [
    "**/dist/**",
    "**/coverage/**",
    "**/.nx/**",
    "**/node_modules/**",
    "**/.tmp/**",
    "**/.cache/**"
  ],

  // Plugin configurations
  eslint: {
    config: [
      "eslint.config.base.ts",
      "eslint.config.react.ts",
      "apps/*/eslint.config.ts",
      "packages/*/eslint.config.ts"
    ]
  },
  vitest: {
    config: [
      "vitest.config.base.ts",
      "vitest.config.react.ts",
      "apps/*/vitest.config.ts",
      "packages/*/vitest.config.ts"
    ]
  },

  // Still disabled due to path issues
  vite: false,
  playwright: false
};

export default config;