/**
 * Re-export all OpenAlex API TypeScript types from shared utils package
 */

// Re-export all types from entities
export type {
  OpenAlexId,
  DOI,
  ORCID,
  RORId,
  ISSNId,
  WikidataId,
  DateString,
  NumericFilter,
  BaseIds,
  WorkIds,
  AuthorIds,
  SourceIds,
  InstitutionIds,
  ConceptIds,
  TopicIds,
  PublisherIds,
  FunderIds,
  KeywordIds,
  ConceptItem,
  TopicItem,
  SummaryStats,
  APCInfo,
  APCPrice,
  PartialExceptId,
  BaseEntity,
  EntityWithWorks,
  CountsByYear,
  Location,
  Institution,
  Authorship,
  Work,
  PartialWork,
  Author,
  PartialAuthor,
  Source,
  InstitutionEntity,
  Concept,
  Topic,
  Publisher,
  Funder,
  Keyword,
  KeywordCountsByYear,
  PartialSource,
  PartialInstitution,
  OpenAlexEntity,
  OpenAlexEntityType as EntityType,
  EntityTypeMap,
  BaseEntityFilters,
  BaseEntityWithTopicsFilters,
  WorksFilters,
  AuthorsFilters,
  SourcesFilters,
  InstitutionsFilters,
  TopicsFilters,
  ConceptsFilters,
  PublishersFilters,
  FundersFilters,
  KeywordsFilters,
  EntityFilters,
  OpenAlexResponse,
  OpenAlexQueryParams as QueryParams,
  StatsParams,
  SampleParams,
  GroupParams,
  AutocompleteResult,
  NGram,
  OpenAlexError,
  TextAnalysis,
} from "@academic-explorer/entities";

// Re-export schemas and type guards
export {
  openAlexIdSchema,
  dateStringSchema,
  countsByYearSchema,
  metaSchema,
  groupBySchema,
  baseEntitySchema,
  workSchema,
  authorSchema,
  institutionSchema,
  openAlexResponseSchema,
  apiResponseSchema,
  workResponseSchema,
  authorResponseSchema,
  institutionResponseSchema,
} from "@academic-explorer/entities";

export {
  isRecord,
  trustObjectShape,
  extractPropertyValue,
  isOpenAlexId,
  isValidDateString,
  isValidWikidataId,
} from "@academic-explorer/entities";
