/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ErrorTestRouteImport } from './routes/error-test'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TextIndexRouteImport } from './routes/text/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as PublishersIndexRouteImport } from './routes/publishers/index'
import { Route as KeywordsIndexRouteImport } from './routes/keywords/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions/index'
import { Route as FundersIndexRouteImport } from './routes/funders/index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as EvaluationResultsRouteImport } from './routes/evaluation/results'
import { Route as EvaluationDatasetsRouteImport } from './routes/evaluation/datasets'
import { Route as TextTopicsIndexRouteImport } from './routes/text/topics/index'
import { Route as TextKeywordsIndexRouteImport } from './routes/text/keywords/index'
import { Route as TextConceptsIndexRouteImport } from './routes/text/concepts/index'
import { Route as AutocompleteWorksIndexRouteImport } from './routes/autocomplete/works/index'
import { Route as AutocompleteSourcesIndexRouteImport } from './routes/autocomplete/sources/index'
import { Route as AutocompletePublishersIndexRouteImport } from './routes/autocomplete/publishers/index'
import { Route as AutocompleteInstitutionsIndexRouteImport } from './routes/autocomplete/institutions/index'
import { Route as AutocompleteFundersIndexRouteImport } from './routes/autocomplete/funders/index'
import { Route as AutocompleteConceptsIndexRouteImport } from './routes/autocomplete/concepts/index'
import { Route as AutocompleteAuthorsIndexRouteImport } from './routes/autocomplete/authors/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/evaluation.lazy').then((d) => d.Route))
const ErrorTestRoute = ErrorTestRouteImport.update({
  id: '/error-test',
  path: '/error-test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error-test.lazy').then((d) => d.Route))
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/catalogue.lazy').then((d) => d.Route))
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cache.lazy').then((d) => d.Route))
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/browse.lazy').then((d) => d.Route))
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bookmarks.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/works/index.lazy').then((d) => d.Route))
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/topics/index.lazy').then((d) => d.Route))
const TextIndexRoute = TextIndexRouteImport.update({
  id: '/text/',
  path: '/text/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/text/index.lazy').then((d) => d.Route))
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sources/index.lazy').then((d) => d.Route))
const PublishersIndexRoute = PublishersIndexRouteImport.update({
  id: '/publishers/',
  path: '/publishers/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/publishers/index.lazy').then((d) => d.Route),
)
const KeywordsIndexRoute = KeywordsIndexRouteImport.update({
  id: '/keywords/',
  path: '/keywords/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/keywords/index.lazy').then((d) => d.Route),
)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/institutions/index.lazy').then((d) => d.Route),
)
const FundersIndexRoute = FundersIndexRouteImport.update({
  id: '/funders/',
  path: '/funders/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/funders/index.lazy').then((d) => d.Route))
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/concepts/index.lazy').then((d) => d.Route),
)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/authors/index.lazy').then((d) => d.Route))
const EvaluationResultsRoute = EvaluationResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => EvaluationRoute,
} as any)
const EvaluationDatasetsRoute = EvaluationDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => EvaluationRoute,
} as any)
const TextTopicsIndexRoute = TextTopicsIndexRouteImport.update({
  id: '/text/topics/',
  path: '/text/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextKeywordsIndexRoute = TextKeywordsIndexRouteImport.update({
  id: '/text/keywords/',
  path: '/text/keywords/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextConceptsIndexRoute = TextConceptsIndexRouteImport.update({
  id: '/text/concepts/',
  path: '/text/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutocompleteWorksIndexRoute = AutocompleteWorksIndexRouteImport.update({
  id: '/autocomplete/works/',
  path: '/autocomplete/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutocompleteSourcesIndexRoute =
  AutocompleteSourcesIndexRouteImport.update({
    id: '/autocomplete/sources/',
    path: '/autocomplete/sources/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocompletePublishersIndexRoute =
  AutocompletePublishersIndexRouteImport.update({
    id: '/autocomplete/publishers/',
    path: '/autocomplete/publishers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocompleteInstitutionsIndexRoute =
  AutocompleteInstitutionsIndexRouteImport.update({
    id: '/autocomplete/institutions/',
    path: '/autocomplete/institutions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocompleteFundersIndexRoute =
  AutocompleteFundersIndexRouteImport.update({
    id: '/autocomplete/funders/',
    path: '/autocomplete/funders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocompleteConceptsIndexRoute =
  AutocompleteConceptsIndexRouteImport.update({
    id: '/autocomplete/concepts/',
    path: '/autocomplete/concepts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocompleteAuthorsIndexRoute =
  AutocompleteAuthorsIndexRouteImport.update({
    id: '/autocomplete/authors/',
    path: '/autocomplete/authors/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/catalogue': typeof CatalogueRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/authors': typeof AuthorsIndexRoute
  '/concepts': typeof ConceptsIndexRoute
  '/funders': typeof FundersIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/keywords': typeof KeywordsIndexRoute
  '/publishers': typeof PublishersIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/text': typeof TextIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/works': typeof WorksIndexRoute
  '/autocomplete/authors': typeof AutocompleteAuthorsIndexRoute
  '/autocomplete/concepts': typeof AutocompleteConceptsIndexRoute
  '/autocomplete/funders': typeof AutocompleteFundersIndexRoute
  '/autocomplete/institutions': typeof AutocompleteInstitutionsIndexRoute
  '/autocomplete/publishers': typeof AutocompletePublishersIndexRoute
  '/autocomplete/sources': typeof AutocompleteSourcesIndexRoute
  '/autocomplete/works': typeof AutocompleteWorksIndexRoute
  '/text/concepts': typeof TextConceptsIndexRoute
  '/text/keywords': typeof TextKeywordsIndexRoute
  '/text/topics': typeof TextTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/catalogue': typeof CatalogueRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/authors': typeof AuthorsIndexRoute
  '/concepts': typeof ConceptsIndexRoute
  '/funders': typeof FundersIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/keywords': typeof KeywordsIndexRoute
  '/publishers': typeof PublishersIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/text': typeof TextIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/works': typeof WorksIndexRoute
  '/autocomplete/authors': typeof AutocompleteAuthorsIndexRoute
  '/autocomplete/concepts': typeof AutocompleteConceptsIndexRoute
  '/autocomplete/funders': typeof AutocompleteFundersIndexRoute
  '/autocomplete/institutions': typeof AutocompleteInstitutionsIndexRoute
  '/autocomplete/publishers': typeof AutocompletePublishersIndexRoute
  '/autocomplete/sources': typeof AutocompleteSourcesIndexRoute
  '/autocomplete/works': typeof AutocompleteWorksIndexRoute
  '/text/concepts': typeof TextConceptsIndexRoute
  '/text/keywords': typeof TextKeywordsIndexRoute
  '/text/topics': typeof TextTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/catalogue': typeof CatalogueRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/authors/': typeof AuthorsIndexRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/funders/': typeof FundersIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/keywords/': typeof KeywordsIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/text/': typeof TextIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/works/': typeof WorksIndexRoute
  '/autocomplete/authors/': typeof AutocompleteAuthorsIndexRoute
  '/autocomplete/concepts/': typeof AutocompleteConceptsIndexRoute
  '/autocomplete/funders/': typeof AutocompleteFundersIndexRoute
  '/autocomplete/institutions/': typeof AutocompleteInstitutionsIndexRoute
  '/autocomplete/publishers/': typeof AutocompletePublishersIndexRoute
  '/autocomplete/sources/': typeof AutocompleteSourcesIndexRoute
  '/autocomplete/works/': typeof AutocompleteWorksIndexRoute
  '/text/concepts/': typeof TextConceptsIndexRoute
  '/text/keywords/': typeof TextKeywordsIndexRoute
  '/text/topics/': typeof TextTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/browse'
    | '/cache'
    | '/catalogue'
    | '/error-test'
    | '/evaluation'
    | '/history'
    | '/search'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/authors'
    | '/concepts'
    | '/funders'
    | '/institutions'
    | '/keywords'
    | '/publishers'
    | '/sources'
    | '/text'
    | '/topics'
    | '/works'
    | '/autocomplete/authors'
    | '/autocomplete/concepts'
    | '/autocomplete/funders'
    | '/autocomplete/institutions'
    | '/autocomplete/publishers'
    | '/autocomplete/sources'
    | '/autocomplete/works'
    | '/text/concepts'
    | '/text/keywords'
    | '/text/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/browse'
    | '/cache'
    | '/catalogue'
    | '/error-test'
    | '/evaluation'
    | '/history'
    | '/search'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/authors'
    | '/concepts'
    | '/funders'
    | '/institutions'
    | '/keywords'
    | '/publishers'
    | '/sources'
    | '/text'
    | '/topics'
    | '/works'
    | '/autocomplete/authors'
    | '/autocomplete/concepts'
    | '/autocomplete/funders'
    | '/autocomplete/institutions'
    | '/autocomplete/publishers'
    | '/autocomplete/sources'
    | '/autocomplete/works'
    | '/text/concepts'
    | '/text/keywords'
    | '/text/topics'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/browse'
    | '/cache'
    | '/catalogue'
    | '/error-test'
    | '/evaluation'
    | '/history'
    | '/search'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/authors/'
    | '/concepts/'
    | '/funders/'
    | '/institutions/'
    | '/keywords/'
    | '/publishers/'
    | '/sources/'
    | '/text/'
    | '/topics/'
    | '/works/'
    | '/autocomplete/authors/'
    | '/autocomplete/concepts/'
    | '/autocomplete/funders/'
    | '/autocomplete/institutions/'
    | '/autocomplete/publishers/'
    | '/autocomplete/sources/'
    | '/autocomplete/works/'
    | '/text/concepts/'
    | '/text/keywords/'
    | '/text/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  BrowseRoute: typeof BrowseRoute
  CacheRoute: typeof CacheRoute
  CatalogueRoute: typeof CatalogueRoute
  ErrorTestRoute: typeof ErrorTestRoute
  EvaluationRoute: typeof EvaluationRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
  FundersIndexRoute: typeof FundersIndexRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  KeywordsIndexRoute: typeof KeywordsIndexRoute
  PublishersIndexRoute: typeof PublishersIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  TextIndexRoute: typeof TextIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
  AutocompleteAuthorsIndexRoute: typeof AutocompleteAuthorsIndexRoute
  AutocompleteConceptsIndexRoute: typeof AutocompleteConceptsIndexRoute
  AutocompleteFundersIndexRoute: typeof AutocompleteFundersIndexRoute
  AutocompleteInstitutionsIndexRoute: typeof AutocompleteInstitutionsIndexRoute
  AutocompletePublishersIndexRoute: typeof AutocompletePublishersIndexRoute
  AutocompleteSourcesIndexRoute: typeof AutocompleteSourcesIndexRoute
  AutocompleteWorksIndexRoute: typeof AutocompleteWorksIndexRoute
  TextConceptsIndexRoute: typeof TextConceptsIndexRoute
  TextKeywordsIndexRoute: typeof TextKeywordsIndexRoute
  TextTopicsIndexRoute: typeof TextTopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-test': {
      id: '/error-test'
      path: '/error-test'
      fullPath: '/error-test'
      preLoaderRoute: typeof ErrorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/': {
      id: '/text/'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers/': {
      id: '/publishers/'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof PublishersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords/': {
      id: '/keywords/'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funders/': {
      id: '/funders/'
      path: '/funders'
      fullPath: '/funders'
      preLoaderRoute: typeof FundersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/results': {
      id: '/evaluation/results'
      path: '/results'
      fullPath: '/evaluation/results'
      preLoaderRoute: typeof EvaluationResultsRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/evaluation/datasets': {
      id: '/evaluation/datasets'
      path: '/datasets'
      fullPath: '/evaluation/datasets'
      preLoaderRoute: typeof EvaluationDatasetsRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/text/topics/': {
      id: '/text/topics/'
      path: '/text/topics'
      fullPath: '/text/topics'
      preLoaderRoute: typeof TextTopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/keywords/': {
      id: '/text/keywords/'
      path: '/text/keywords'
      fullPath: '/text/keywords'
      preLoaderRoute: typeof TextKeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/concepts/': {
      id: '/text/concepts/'
      path: '/text/concepts'
      fullPath: '/text/concepts'
      preLoaderRoute: typeof TextConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/works/': {
      id: '/autocomplete/works/'
      path: '/autocomplete/works'
      fullPath: '/autocomplete/works'
      preLoaderRoute: typeof AutocompleteWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/sources/': {
      id: '/autocomplete/sources/'
      path: '/autocomplete/sources'
      fullPath: '/autocomplete/sources'
      preLoaderRoute: typeof AutocompleteSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/publishers/': {
      id: '/autocomplete/publishers/'
      path: '/autocomplete/publishers'
      fullPath: '/autocomplete/publishers'
      preLoaderRoute: typeof AutocompletePublishersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/institutions/': {
      id: '/autocomplete/institutions/'
      path: '/autocomplete/institutions'
      fullPath: '/autocomplete/institutions'
      preLoaderRoute: typeof AutocompleteInstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/funders/': {
      id: '/autocomplete/funders/'
      path: '/autocomplete/funders'
      fullPath: '/autocomplete/funders'
      preLoaderRoute: typeof AutocompleteFundersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/concepts/': {
      id: '/autocomplete/concepts/'
      path: '/autocomplete/concepts'
      fullPath: '/autocomplete/concepts'
      preLoaderRoute: typeof AutocompleteConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/authors/': {
      id: '/autocomplete/authors/'
      path: '/autocomplete/authors'
      fullPath: '/autocomplete/authors'
      preLoaderRoute: typeof AutocompleteAuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EvaluationRouteChildren {
  EvaluationDatasetsRoute: typeof EvaluationDatasetsRoute
  EvaluationResultsRoute: typeof EvaluationResultsRoute
}

const EvaluationRouteChildren: EvaluationRouteChildren = {
  EvaluationDatasetsRoute: EvaluationDatasetsRoute,
  EvaluationResultsRoute: EvaluationResultsRoute,
}

const EvaluationRouteWithChildren = EvaluationRoute._addFileChildren(
  EvaluationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  BrowseRoute: BrowseRoute,
  CacheRoute: CacheRoute,
  CatalogueRoute: CatalogueRoute,
  ErrorTestRoute: ErrorTestRoute,
  EvaluationRoute: EvaluationRouteWithChildren,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
  FundersIndexRoute: FundersIndexRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  KeywordsIndexRoute: KeywordsIndexRoute,
  PublishersIndexRoute: PublishersIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  TextIndexRoute: TextIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
  AutocompleteAuthorsIndexRoute: AutocompleteAuthorsIndexRoute,
  AutocompleteConceptsIndexRoute: AutocompleteConceptsIndexRoute,
  AutocompleteFundersIndexRoute: AutocompleteFundersIndexRoute,
  AutocompleteInstitutionsIndexRoute: AutocompleteInstitutionsIndexRoute,
  AutocompletePublishersIndexRoute: AutocompletePublishersIndexRoute,
  AutocompleteSourcesIndexRoute: AutocompleteSourcesIndexRoute,
  AutocompleteWorksIndexRoute: AutocompleteWorksIndexRoute,
  TextConceptsIndexRoute: TextConceptsIndexRoute,
  TextKeywordsIndexRoute: TextKeywordsIndexRoute,
  TextTopicsIndexRoute: TextTopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
