/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ErrorTestRouteImport } from './routes/error-test'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExternalIdRouteImport } from './routes/$externalId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as TopicsTopicIdRouteImport } from './routes/topics/$topicId'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$sourceId'
import { Route as InstitutionsInstitutionIdRouteImport } from './routes/institutions/$institutionId'
import { Route as HttpsSplatRouteImport } from './routes/https/$'
import { Route as ExploreGraphRouteImport } from './routes/explore/graph'
import { Route as EvaluationResultsRouteImport } from './routes/evaluation/results'
import { Route as EvaluationDatasetsRouteImport } from './routes/evaluation/datasets'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors/$authorId'
import { Route as WorksDoiDoiRouteImport } from './routes/works/doi.$doi'
import { Route as SourcesIssnIssnRouteImport } from './routes/sources/issn.$issn'
import { Route as InstitutionsRorRorRouteImport } from './routes/institutions/ror.$ror'
import { Route as AuthorsOrcidOrcidRouteImport } from './routes/authors/orcid.$orcid'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorTestRoute = ErrorTestRouteImport.update({
  id: '/error-test',
  path: '/error-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalIdRoute = ExternalIdRouteImport.update({
  id: '/$externalId',
  path: '/$externalId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsInstitutionIdRoute =
  InstitutionsInstitutionIdRouteImport.update({
    id: '/institutions/$institutionId',
    path: '/institutions/$institutionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HttpsSplatRoute = HttpsSplatRouteImport.update({
  id: '/https/$',
  path: '/https/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreGraphRoute = ExploreGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ExploreRoute,
} as any)
const EvaluationResultsRoute = EvaluationResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => EvaluationRoute,
} as any)
const EvaluationDatasetsRoute = EvaluationDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => EvaluationRoute,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksDoiDoiRoute = WorksDoiDoiRouteImport.update({
  id: '/works/doi/$doi',
  path: '/works/doi/$doi',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIssnIssnRoute = SourcesIssnIssnRouteImport.update({
  id: '/sources/issn/$issn',
  path: '/sources/issn/$issn',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRorRorRoute = InstitutionsRorRorRouteImport.update({
  id: '/institutions/ror/$ror',
  path: '/institutions/ror/$ror',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsOrcidOrcidRoute = AuthorsOrcidOrcidRouteImport.update({
  id: '/authors/orcid/$orcid',
  path: '/authors/orcid/$orcid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$externalId': typeof ExternalIdRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/search': typeof SearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/explore/graph': typeof ExploreGraphRoute
  '/https/$': typeof HttpsSplatRoute
  '/institutions/$institutionId': typeof InstitutionsInstitutionIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors/orcid/$orcid': typeof AuthorsOrcidOrcidRoute
  '/institutions/ror/$ror': typeof InstitutionsRorRorRoute
  '/sources/issn/$issn': typeof SourcesIssnIssnRoute
  '/works/doi/$doi': typeof WorksDoiDoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$externalId': typeof ExternalIdRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/search': typeof SearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/explore/graph': typeof ExploreGraphRoute
  '/https/$': typeof HttpsSplatRoute
  '/institutions/$institutionId': typeof InstitutionsInstitutionIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors/orcid/$orcid': typeof AuthorsOrcidOrcidRoute
  '/institutions/ror/$ror': typeof InstitutionsRorRorRoute
  '/sources/issn/$issn': typeof SourcesIssnIssnRoute
  '/works/doi/$doi': typeof WorksDoiDoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$externalId': typeof ExternalIdRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/cache': typeof CacheRoute
  '/error-test': typeof ErrorTestRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/search': typeof SearchRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/evaluation/datasets': typeof EvaluationDatasetsRoute
  '/evaluation/results': typeof EvaluationResultsRoute
  '/explore/graph': typeof ExploreGraphRoute
  '/https/$': typeof HttpsSplatRoute
  '/institutions/$institutionId': typeof InstitutionsInstitutionIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/authors/orcid/$orcid': typeof AuthorsOrcidOrcidRoute
  '/institutions/ror/$ror': typeof InstitutionsRorRorRoute
  '/sources/issn/$issn': typeof SourcesIssnIssnRoute
  '/works/doi/$doi': typeof WorksDoiDoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$externalId'
    | '/about'
    | '/browse'
    | '/cache'
    | '/error-test'
    | '/evaluation'
    | '/explore'
    | '/search'
    | '/authors/$authorId'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/explore/graph'
    | '/https/$'
    | '/institutions/$institutionId'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/works/$workId'
    | '/authors/orcid/$orcid'
    | '/institutions/ror/$ror'
    | '/sources/issn/$issn'
    | '/works/doi/$doi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$externalId'
    | '/about'
    | '/browse'
    | '/cache'
    | '/error-test'
    | '/evaluation'
    | '/explore'
    | '/search'
    | '/authors/$authorId'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/explore/graph'
    | '/https/$'
    | '/institutions/$institutionId'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/works/$workId'
    | '/authors/orcid/$orcid'
    | '/institutions/ror/$ror'
    | '/sources/issn/$issn'
    | '/works/doi/$doi'
  id:
    | '__root__'
    | '/'
    | '/$externalId'
    | '/about'
    | '/browse'
    | '/cache'
    | '/error-test'
    | '/evaluation'
    | '/explore'
    | '/search'
    | '/authors/$authorId'
    | '/evaluation/datasets'
    | '/evaluation/results'
    | '/explore/graph'
    | '/https/$'
    | '/institutions/$institutionId'
    | '/sources/$sourceId'
    | '/topics/$topicId'
    | '/works/$workId'
    | '/authors/orcid/$orcid'
    | '/institutions/ror/$ror'
    | '/sources/issn/$issn'
    | '/works/doi/$doi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExternalIdRoute: typeof ExternalIdRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  CacheRoute: typeof CacheRoute
  ErrorTestRoute: typeof ErrorTestRoute
  EvaluationRoute: typeof EvaluationRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  SearchRoute: typeof SearchRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  HttpsSplatRoute: typeof HttpsSplatRoute
  InstitutionsInstitutionIdRoute: typeof InstitutionsInstitutionIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  AuthorsOrcidOrcidRoute: typeof AuthorsOrcidOrcidRoute
  InstitutionsRorRorRoute: typeof InstitutionsRorRorRoute
  SourcesIssnIssnRoute: typeof SourcesIssnIssnRoute
  WorksDoiDoiRoute: typeof WorksDoiDoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-test': {
      id: '/error-test'
      path: '/error-test'
      fullPath: '/error-test'
      preLoaderRoute: typeof ErrorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$externalId': {
      id: '/$externalId'
      path: '/$externalId'
      fullPath: '/$externalId'
      preLoaderRoute: typeof ExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$institutionId': {
      id: '/institutions/$institutionId'
      path: '/institutions/$institutionId'
      fullPath: '/institutions/$institutionId'
      preLoaderRoute: typeof InstitutionsInstitutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/https/$': {
      id: '/https/$'
      path: '/https/$'
      fullPath: '/https/$'
      preLoaderRoute: typeof HttpsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/graph': {
      id: '/explore/graph'
      path: '/graph'
      fullPath: '/explore/graph'
      preLoaderRoute: typeof ExploreGraphRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/evaluation/results': {
      id: '/evaluation/results'
      path: '/results'
      fullPath: '/evaluation/results'
      preLoaderRoute: typeof EvaluationResultsRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/evaluation/datasets': {
      id: '/evaluation/datasets'
      path: '/datasets'
      fullPath: '/evaluation/datasets'
      preLoaderRoute: typeof EvaluationDatasetsRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/doi/$doi': {
      id: '/works/doi/$doi'
      path: '/works/doi/$doi'
      fullPath: '/works/doi/$doi'
      preLoaderRoute: typeof WorksDoiDoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/issn/$issn': {
      id: '/sources/issn/$issn'
      path: '/sources/issn/$issn'
      fullPath: '/sources/issn/$issn'
      preLoaderRoute: typeof SourcesIssnIssnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/ror/$ror': {
      id: '/institutions/ror/$ror'
      path: '/institutions/ror/$ror'
      fullPath: '/institutions/ror/$ror'
      preLoaderRoute: typeof InstitutionsRorRorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/orcid/$orcid': {
      id: '/authors/orcid/$orcid'
      path: '/authors/orcid/$orcid'
      fullPath: '/authors/orcid/$orcid'
      preLoaderRoute: typeof AuthorsOrcidOrcidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EvaluationRouteChildren {
  EvaluationDatasetsRoute: typeof EvaluationDatasetsRoute
  EvaluationResultsRoute: typeof EvaluationResultsRoute
}

const EvaluationRouteChildren: EvaluationRouteChildren = {
  EvaluationDatasetsRoute: EvaluationDatasetsRoute,
  EvaluationResultsRoute: EvaluationResultsRoute,
}

const EvaluationRouteWithChildren = EvaluationRoute._addFileChildren(
  EvaluationRouteChildren,
)

interface ExploreRouteChildren {
  ExploreGraphRoute: typeof ExploreGraphRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreGraphRoute: ExploreGraphRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExternalIdRoute: ExternalIdRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  CacheRoute: CacheRoute,
  ErrorTestRoute: ErrorTestRoute,
  EvaluationRoute: EvaluationRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  SearchRoute: SearchRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  HttpsSplatRoute: HttpsSplatRoute,
  InstitutionsInstitutionIdRoute: InstitutionsInstitutionIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  AuthorsOrcidOrcidRoute: AuthorsOrcidOrcidRoute,
  InstitutionsRorRorRoute: InstitutionsRorRorRoute,
  SourcesIssnIssnRoute: SourcesIssnIssnRoute,
  WorksDoiDoiRoute: WorksDoiDoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
