import { ESLintUtils } from "@typescript-eslint/utils";
import * as path from "path";

const createRule = ESLintUtils.RuleCreator(
  (name) => `https://github.com/Mearman/BibGraph/blob/main/tools/eslint-rules/${name}.md`
);

const BARRELSBY_HEADER = "@file Automatically generated by barrelsby.";

// Directories managed by barrelsby (from .barrelsby.json)
const BARRELSBY_DIRECTORIES = [
  "packages/algorithms/src",
  "packages/client/src",
  "packages/types/src",
  "packages/ui/src",
  "packages/utils/src",
  "apps/web/src/components",
];

export const barrelsbyHeader = createRule({
  name: "barrelsby-header",
  meta: {
    type: "problem",
    docs: {
      description: "Enforce barrelsby header in index.ts files within barrelsby-managed directories",
    },
    messages: {
      missingHeader: "index.ts files in barrelsby-managed directories must have the barrelsby header: '{{ expected }}'",
      wrongHeader: "index.ts has incorrect header. Expected barrelsby header: '{{ expected }}'",
    },
    schema: [],
    fixable: "code",
  },
  defaultOptions: [],
  create(context) {
    const filename = context.filename;
    const basename = path.basename(filename);

    // Only check index.ts files
    if (basename !== "index.ts") {
      return {};
    }

    // Check if file is in a barrelsby-managed directory
    const isInBarrelsbyDir = BARRELSBY_DIRECTORIES.some((dir) => {
      const normalizedDir = dir.replace(/^\.\//, "");
      return filename.includes(normalizedDir);
    });

    if (!isInBarrelsbyDir) {
      return {};
    }

    return {
      Program() {
        const sourceCode = context.sourceCode;
        const comments = sourceCode.getAllComments();

        // Find the first block comment at the start of the file
        const firstBlockComment = comments.find(
          (comment) => comment.type === "Block" && comment.range[0] === 0
        );

        // Check if we have a valid barrelsby header
        if (firstBlockComment && firstBlockComment.value.includes(BARRELSBY_HEADER)) {
          // Valid header exists
          return;
        }

        // Report and fix
        if (firstBlockComment) {
          // Block comment exists but doesn't have barrelsby header
          context.report({
            loc: firstBlockComment.loc,
            messageId: "wrongHeader",
            data: { expected: BARRELSBY_HEADER },
            fix(fixer) {
              return fixer.replaceTextRange(
                firstBlockComment.range,
                `/**\n * ${BARRELSBY_HEADER}\n */`
              );
            },
          });
        } else {
          // No block comment at start - need to add header
          context.report({
            loc: { line: 1, column: 0 },
            messageId: "missingHeader",
            data: { expected: BARRELSBY_HEADER },
            fix(fixer) {
              return fixer.insertTextBeforeRange(
                [0, 0],
                `/**\n * ${BARRELSBY_HEADER}\n */\n\n`
              );
            },
          });
        }
      },
    };
  },
});
