/**
 * @file Automatically generated by barrelsby.
 */

// Re-export individual modules to maintain compatibility without barrel patterns

// From bookmark.ts
export type { BookmarkMetadata, Bookmark } from "./bookmark";
export { BookmarkMetadataSchema, BookmarkSchema } from "./bookmark";

// From concepts.ts
export type { ConceptRelationship, ConceptGraphEdge } from "./concepts";
export { createConceptGraphEdge, isConceptRelationship } from "./concepts";

// From expansion-settings.ts
export type {
  ExpansionTarget,
  ExpansionOptions,
  SortCriteria,
  FilterOperator,
  FilterCriteria,
  ExpansionSettings,
  PropertyType,
  PropertyDefinition,
  EntityTypeProperties
} from "./expansion-settings";
export {
  ENTITY_PROPERTIES,
  DEFAULT_EXPANSION_SETTINGS,
  getPropertiesForTarget,
  getDefaultSettingsForTarget,
  validateFilterCriteria
} from "./expansion-settings";

// From grants.ts
export type { GrantRelationship, GrantGraphEdge } from "./grants";
export { createGrantGraphEdge, isGrantRelationship } from "./grants";

// From graph-index-types.ts
export type {
  CompletenessStatus,
  GraphNodeRecord,
  AuthorPosition,
  PublicationVersion,
  GraphEdgeRecord,
  GraphNodeInput,
  GraphEdgeInput,
  EdgePropertyFilter,
  EdgeDirectionFilter,
  NeighborQueryOptions,
  SubgraphResult,
  GraphStatistics
} from "./graph-index-types";
export {
  GRAPH_INDEX_DB_NAME,
  GRAPH_INDEX_DB_VERSION,
  GRAPH_INDEX_TABLES,
  NODE_INDEXES,
  EDGE_INDEXES
} from "./graph-index-types";

// From graph-types.ts
export type {
  Position,
  ExternalIdentifier,
  GraphNode,
  EdgeDirection,
  GraphEdge,
  GraphLayout,
  GraphEvents,
  GraphOptions,
  EntityIdentifier,
  ProviderType,
  SearchOptions,
  SearchResult,
  GraphData,
  GraphCache,
  GraphStats,
  Community,
  ForceLink,
  ForceSimulationNode,
  ForceSimulationTask,
  Position3D,
  ViewMode,
  ControlMode,
  GraphNode3D,
  GraphEdge3D,
  BoundingBox3D,
  CameraState3D,
  CameraAnimation,
  ControlSettings,
  LODConfig,
  DetailLevel,
  PerformanceMetrics3D,
  GraphData3D,
  Visualization3DPreferences
} from "./graph-types";
export {
  isPosition3D,
  isGraphNode3D,
  isCameraState3D
} from "./graph-types";

// From keywords.ts
export type { KeywordRelationship, KeywordGraphEdge } from "./keywords";
export { createKeywordGraphEdge, isKeywordRelationship } from "./keywords";

// From relationships.ts
export { RelationType } from "./relationships";

// From repositories.ts
export type { RepositoryRelationship, RepositoryGraphEdge } from "./repositories";
export { createRepositoryGraphEdge, isRepositoryRelationship } from "./repositories";

// From roles.ts
export type { RoleRelationship, RoleGraphEdge } from "./roles";
export { createRoleGraphEdge, isRoleRelationship } from "./roles";

// From topics.ts
export type { EnhancedTopicRelationship, EnhancedTopicGraphEdge } from "./topics";
export { createEnhancedTopicGraphEdge, isEnhancedTopicRelationship } from "./topics";

// From traversal-types.ts
export type {
  WeightableEdgeProperty,
  WeightFunction,
  WeightConfig,
  TraversalDirection,
  TraversalOptions,
  WeightedPathResult,
  PathfindingOptions
} from "./traversal-types";

// From entities module
export * from "./entities";

// Essential core types that must be available from main package
export type {
  OpenAlexResponse,
  QueryParams,
  SampleParams,
  StatsParams,
  GroupParams,
  AutocompleteResult,
  BaseAutocompleteOptions,
  GroupedResponse
} from "./entities/common";

// Export concept-specific types
export type {
  ConceptsQueryParams,
  ConceptSearchOptions
} from "./entities/concepts";

// Export OpenAlex ID and base entity types
export type {
  OpenAlexId
} from "./entities/base";

export type {
  BaseEntity
} from "./entities/entities";

