import { createTheme } from "@vanilla-extract/css";
import { baseThemeContract, type ColorScheme, type ColorMode } from "./theme-contracts";
import { mantineTheme, componentLibraries } from "./component-libraries.css";

// Color scheme definitions
const colorSchemes = {
  blue: {
    light: {
      primary: "#228be6",
      primaryHover: "#1c7ed6",
      primaryLight: "#74c0fc",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#228be6",
      buttonHover: "#1c7ed6",
    },
    dark: {
      primary: "#339af0",
      primaryHover: "#228be6",
      primaryLight: "#74c0fc",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#339af0",
      buttonHover: "#228be6",
    },
  },
  green: {
    light: {
      primary: "#37b24d",
      primaryHover: "#2f9e44",
      primaryLight: "#8ce99a",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#37b24d",
      buttonHover: "#2f9e44",
    },
    dark: {
      primary: "#51cf66",
      primaryHover: "#37b24d",
      primaryLight: "#8ce99a",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#51cf66",
      buttonHover: "#37b24d",
    },
  },
  orange: {
    light: {
      primary: "#fd7e14",
      primaryHover: "#e8590c",
      primaryLight: "#ffa94d",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#fd7e14",
      buttonHover: "#e8590c",
    },
    dark: {
      primary: "#ff922b",
      primaryHover: "#fd7e14",
      primaryLight: "#ffa94d",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#ff922b",
      buttonHover: "#fd7e14",
    },
  },
  purple: {
    light: {
      primary: "#9775fa",
      primaryHover: "#845ef7",
      primaryLight: "#b197fc",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#9775fa",
      buttonHover: "#845ef7",
    },
    dark: {
      primary: "#ae75fc",
      primaryHover: "#9775fa",
      primaryLight: "#b197fc",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#ae75fc",
      buttonHover: "#9775fa",
    },
  },
  red: {
    light: {
      primary: "#fa5252",
      primaryHover: "#f03e3e",
      primaryLight: "#ff8787",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#fa5252",
      buttonHover: "#f03e3e",
    },
    dark: {
      primary: "#ff6b6b",
      primaryHover: "#fa5252",
      primaryLight: "#ff8787",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#ff6b6b",
      buttonHover: "#fa5252",
    },
  },
  neutral: {
    light: {
      primary: "#495057",
      primaryHover: "#343a40",
      primaryLight: "#868e96",
      background: "#ffffff",
      backgroundHover: "#f8f9fa",
      surface: "#ffffff",
      border: "#dee2e6",
      text: "#212529",
      textSecondary: "#495057",
      textMuted: "#868e96",
      card: "#ffffff",
      input: "#ffffff",
      button: "#495057",
      buttonHover: "#343a40",
    },
    dark: {
      primary: "#868e96",
      primaryHover: "#495057",
      primaryLight: "#adb5bd",
      background: "#1a1b1e",
      backgroundHover: "#25262b",
      surface: "#2c2e33",
      border: "#373a40",
      text: "#ffffff",
      textSecondary: "#adb5bd",
      textMuted: "#868e96",
      card: "#25262b",
      input: "#1a1b1e",
      button: "#868e96",
      buttonHover: "#495057",
    },
  },
} as const;

// Export color scheme function to get colors by scheme and mode
export function getColorScheme(scheme: ColorScheme, mode: ColorMode) {
  return colorSchemes[scheme][mode];
}

// Helper function to get colors by scheme and mode
export function getColorThemeTokens(scheme: ColorScheme, mode: ColorMode) {
  const colors = getColorScheme(scheme, mode);
  const mantineTokens = componentLibraries.mantine; // Use mantine tokens for spacing/borders/shadows

  return {
    colors,
    spacing: mantineTokens.spacing,
    borders: mantineTokens.borders,
    shadows: mantineTokens.shadows,
  };
}