/**
 * @file Automatically generated by barrelsby.
 */

export type { EntityType, OpenAlexEntity } from "./entities";
export type { BaseEntity, Author, Work, Institution, Source, Publisher, Funder, Concept, Domain, Field, Subfield, Topic, Keyword, InstitutionEntity } from "./entities";

// Export filter types that were previously available through barrels
export type {
  WorksFilters,
  AuthorsFilters,
  SourcesFilters,
  InstitutionsFilters,
  TopicsFilters,
  ConceptsFilters,
  PublishersFilters,
  FundersFilters,
  KeywordsFilters,
  BaseEntityFilters,
  BaseEntityWithTopicsFilters,
  EntityFilters
} from "./filters";

// Export author-specific types that were previously available through barrels
export type {
  AuthorGroupingOptions,
  AuthorCollaboratorsFilters,
  AuthorAutocompleteOptions,
  AuthorWorksFilters,
  AuthorSearchOptions,
  GroupByResult
} from "./authors";
export {
  getEntityRelationshipQueries,
  getInboundQueries,
  getOutboundQueries,
  hasInboundQueries,
  hasOutboundQueries,
  ENTITY_RELATIONSHIP_QUERIES
} from "./relationship-queries";
export {
  ENTITY_METADATA,
  getEntityMetadata,
  getEntitySingularForm,
  getEntityIdPrefix,
  getEntityRoutePath,
  getEntityIcon,
  getEntityColor,
  getEntityDisplayName,
  getEntityPlural,
  toEntityType,
  toSingularForm,
  isEntityType,
  detectEntityType
} from "./entity-metadata";
export { getEntityType, isOpenAlexEntity } from "./type-guards";
export { validateWithSchema, trustObjectShape, extractPropertyValue } from "./utils";
export { isOpenAlexId } from "./validation";
export type { OpenAlexError, AutocompleteResult } from "./common";

// Export graph-list types that were previously available through barrels
export type {
  GraphListNode,
  AddToGraphListParams,
  PruneGraphListResult
} from "../graph/graph-list";
export {
  GRAPH_LIST_CONFIG
} from "../graph/graph-list";